# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Update versions with:
#   pre-commit autoupdate --freeze && pre-commit run -a
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3 # Defaults to python2, so override it.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: 6e41aba91fb32e9feb741a6258eefeb9c6e4a482 # frozen: v2.2.6
    hooks:
      - id: codespell
  - repo: https://github.com/google/pre-commit-tool-hooks
    rev: e006c8ab09f96ec32ba728b488ea5d17e1f8f6c0 # frozen: v1.2.4
    hooks:
      - id: check-copyright
      - id: check-google-doc-style
      - id: markdown-toc
  # Formatters should be run late so that they can re-format any prior changes.
  - repo: https://github.com/psf/black
    rev: 3702ba224ecffbcec30af640c149f231d90aebdb # frozen: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/prettier/pre-commit
    rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
    hooks:
      - id: prettier
  # Run linters last, as formatters and other checks may fix issues.
  - repo: https://github.com/PyCQA/flake8
    rev: 7d37d9032d0d161634be4554273c30efd4dea0b3 # frozen: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: e5ea6670624c24f8321f6328ef3176dbba76db46 # frozen: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
